version: "3.7"

services:
  digital_wallet_app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/digiwallet
    hostname: digital_wallet_app
    container_name: digital_wallet_app

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /home/dev/devs/ora/mongo:/data/db
    hostname: mongo
    container_name: mongo
